=== Allgemeine Informationen zur Applikation

==== Name und Version der Applikation

Die in diesem Handbuch beschriebene Anwendung trägt den Namen 
ifdef::cgs-assist[] 
{cgs-application}
endif::cgs-assist[]
ifdef::arc-assist[]
{arc-application}
endif::arc-assist[]
 und liegt in der aktuellen Version {revnumber} vom {revdate} vor.

==== Übersicht und Funktionen

ifdef::cgs-assist[] 
*{cgs-application}*
endif::cgs-assist[]
ifdef::arc-assist[]
*{arc-application}*
endif::arc-assist[]
 ist eine *browserbasierte Webanwendung*, die lokal beim Kunden gehostet wird. 
Der Betrieb erfolgt in *Docker-Containern* auf einem *Linux-Server* (entweder *on-premise* oder in einer *Cloud-VM*). 
Die Anwendung dient zur Nutzung von KI-Sprachmodellen (Large Language Models, LLMs), welche über eine externe API angebunden werden, u. a. Azure OpenAI. 
Mit 
ifdef::cgs-assist[] 
*{cgs-application}*
endif::cgs-assist[]
ifdef::arc-assist[]
*{arc-application}*
endif::arc-assist[]
 können Nutzer effizient Dokumente analysieren, Abfragen stellen und Daten verarbeiten, basierend auf KI-Technologien.

ifdef::cgs-assist[] 
*{cgs-application}*
endif::cgs-assist[]
ifdef::arc-assist[]
*{arc-application}*
endif::arc-assist[]
 wird ohne eigene(s) KI-Sprachmodell(e) ausgeliefert. Stattdessen greift das Tool über eine API-Anbindung auf 
die *LLM-Infrastruktur des Kunden* zurück. Damit 
ifdef::cgs-assist[] 
*{cgs-application}*
endif::cgs-assist[]
ifdef::arc-assist[]
*{arc-application}*
endif::arc-assist[]
 ein Sprachmodell nutzen kann, muss eine funktionsfähige Anbindung 
an ein unterstütztes LLM eingerichtet werden.

==== Lizenzinformationen

Für die Nutzung von 
ifdef::cgs-assist[] 
{cgs-application}
endif::cgs-assist[]
ifdef::arc-assist[]
{arc-application}
endif::arc-assist[]
 wird eine Unternehmenslizenz der 
 ifdef::cgs-assist[] 
CGS 
endif::cgs-assist[]
ifdef::arc-assist[]
Arc 
endif::arc-assist[]
 verwendet. 
Die Lizenz entspricht dem Modell "Concurrent User" für bis zu 100 gleichzeitige Nutzer. 
Wartungs- und Update-Leistungen sind während der vertraglich vereinbarten Laufzeit enthalten.  
Die Lizenzbedingungen sind im Vertrag mit dem Hersteller und in den unternehmenseigenen IT-Richtlinien hinterlegt. 
Die Einhaltung der Lizenzbedingungen wird regelmäßig durch die IT-Abteilung geprüft.
